import type { UnitCategory, CategoryConfig } from "@/types/units";
import { units } from "@/config/units";
import {
  convertLength,
  convertWeight,
  convertTemperature,
  convertArea,
  convertVolume,
  convertSpeed,
  convertTime,
  convertDigital,
  convertPressure,
  convertEnergy,
  convertAngle,
  convertDataRate,
  convertVolumeDry,
  convertCurrency,
  convertCase,
  convertPower,
  convertForce,
  convertFuelConsumption,
  convertNumbers,
} from "@/utils/conversions";

export const commonCategoryConfigs: Partial<
  Record<UnitCategory, CategoryConfig>
> = {
  volume_dry: {
    title: "Dry Volume Converter",
    units: units.volume_dry,
    convertFn: convertVolumeDry,
    defaultFrom: "dry_quarts",
    defaultTo: "dry_pints",
  },
  currency: {
    title: "Currency Converter",
    units: units.currency,
    convertFn: convertCurrency,
    defaultFrom: "usd",
    defaultTo: "eur",
  },
  case: {
    title: "Case Converter",
    units: units.case,
    convertFn: convertCase,
    defaultFrom: "lowercase",
    defaultTo: "uppercase",
  },
  power: {
    title: "Power Converter",
    units: units.power,
    convertFn: convertPower,
    defaultFrom: "watt",
    defaultTo: "kilowatt",
  },
  force: {
    title: "Force Converter",
    units: units.force,
    convertFn: convertForce,
    defaultFrom: "newton",
    defaultTo: "kilonewton",
  },
  fuel_consumption: {
    title: "Fuel Consumption Converter",
    units: units.fuel_consumption,
    convertFn: convertFuelConsumption,
    defaultFrom: "miles_per_gallon",
    defaultTo: "kilometers_per_liter",
  },
  numbers: {
    title: "Number Base Converter",
    units: units.numbers,
    convertFn: convertNumbers,
    defaultFrom: "decimal",
    defaultTo: "binary",
  },
  length: {
    title: "Length Converter",
    units: units.length,
    convertFn: convertLength,
    defaultFrom: "meters",
    defaultTo: "feet",
  },
  weight: {
    title: "Weight Converter",
    units: units.weight,
    convertFn: convertWeight,
    defaultFrom: "kilograms",
    defaultTo: "pounds",
  },
  temperature: {
    title: "Temperature Converter",
    units: units.temperature,
    convertFn: convertTemperature,
    defaultFrom: "celsius",
    defaultTo: "fahrenheit",
  },
  area: {
    title: "Area Converter",
    units: units.area,
    convertFn: convertArea,
    defaultFrom: "square_meters",
    defaultTo: "square_feet",
  },
  volume: {
    title: "Volume Converter",
    units: units.volume,
    convertFn: convertVolume,
    defaultFrom: "liters",
    defaultTo: "gallons",
  },
  speed: {
    title: "Speed Converter",
    units: units.speed,
    convertFn: convertSpeed,
    defaultFrom: "meters_per_second",
    defaultTo: "kilometers_per_hour",
  },
  time: {
    title: "Time Converter",
    units: units.time,
    convertFn: convertTime,
    defaultFrom: "seconds",
    defaultTo: "minutes",
  },
  digital: {
    title: "Digital Storage Converter",
    units: units.digital,
    convertFn: convertDigital,
    defaultFrom: "bytes",
    defaultTo: "kilobytes",
  },
  pressure: {
    title: "Pressure Converter",
    units: units.pressure,
    convertFn: convertPressure,
    defaultFrom: "pascal",
    defaultTo: "bar",
  },
  energy: {
    title: "Energy Converter",
    units: units.energy,
    convertFn: convertEnergy,
    defaultFrom: "joule",
    defaultTo: "calorie",
  },
  angle: {
    title: "Angle Converter",
    units: units.angle,
    convertFn: convertAngle,
    defaultFrom: "degree",
    defaultTo: "radian",
  },
  data_rate: {
    title: "Data Transfer Rate Converter",
    units: units.data_rate,
    convertFn: convertDataRate,
    defaultFrom: "bits_per_second",
    defaultTo: "kilobits_per_second",
  },
};
