import type { UnitCategory, CategoryConfig } from "@/types/units";
import { units } from "@/config/units";
import {
  convertCharge,
  convertLinearChargeDensity,
  convertSurfaceChargeDensity,
  convertVolumeChargeDensity,
  convertCurrent,
  convertLinearCurrentDensity,
  convertSurfaceCurrentDensity,
  convertElectricFieldStrength,
  convertElectricPotential,
  convertElectricResistance,
  convertElectricResistivity,
  convertElectricConductance,
  convertElectricConductivity,
  convertElectrostaticCapacitance,
  convertInductance,
} from "@/utils/conversions";

export const electricityCategoryConfigs: Partial<
  Record<UnitCategory, CategoryConfig>
> = {
  charge: {
    title: "Charge Converter",
    units: units.charge,
    convertFn: convertCharge,
    defaultFrom: "coulomb",
    defaultTo: "millicoulomb",
  },
  linear_charge_density: {
    title: "Linear Charge Density Converter",
    units: units.linear_charge_density,
    convertFn: convertLinearChargeDensity,
    defaultFrom: "coulomb_per_meter",
    defaultTo: "coulomb_per_centimeter",
  },
  surface_charge_density: {
    title: "Surface Charge Density Converter",
    units: units.surface_charge_density,
    convertFn: convertSurfaceChargeDensity,
    defaultFrom: "coulomb_per_square_meter",
    defaultTo: "coulomb_per_square_centimeter",
  },
  volume_charge_density: {
    title: "Volume Charge Density Converter",
    units: units.volume_charge_density,
    convertFn: convertVolumeChargeDensity,
    defaultFrom: "coulomb_per_cubic_meter",
    defaultTo: "coulomb_per_cubic_centimeter",
  },
  current: {
    title: "Current Converter",
    units: units.current,
    convertFn: convertCurrent,
    defaultFrom: "ampere",
    defaultTo: "milliampere",
  },
  linear_current_density: {
    title: "Linear Current Density Converter",
    units: units.linear_current_density,
    convertFn: convertLinearCurrentDensity,
    defaultFrom: "ampere_per_meter",
    defaultTo: "ampere_per_centimeter",
  },
  surface_current_density: {
    title: "Surface Current Density Converter",
    units: units.surface_current_density,
    convertFn: convertSurfaceCurrentDensity,
    defaultFrom: "ampere_per_square_meter",
    defaultTo: "ampere_per_square_centimeter",
  },
  electric_field_strength: {
    title: "Electric Field Strength Converter",
    units: units.electric_field_strength,
    convertFn: convertElectricFieldStrength,
    defaultFrom: "volt_per_meter",
    defaultTo: "volt_per_centimeter",
  },
  electric_potential: {
    title: "Electric Potential Converter",
    units: units.electric_potential,
    convertFn: convertElectricPotential,
    defaultFrom: "volt",
    defaultTo: "millivolt",
  },
  electric_resistance: {
    title: "Electric Resistance Converter",
    units: units.electric_resistance,
    convertFn: convertElectricResistance,
    defaultFrom: "ohm",
    defaultTo: "milliohm",
  },
  electric_resistivity: {
    title: "Electric Resistivity Converter",
    units: units.electric_resistivity,
    convertFn: convertElectricResistivity,
    defaultFrom: "ohm_meter",
    defaultTo: "ohm_centimeter",
  },
  electric_conductance: {
    title: "Electric Conductance Converter",
    units: units.electric_conductance,
    convertFn: convertElectricConductance,
    defaultFrom: "siemens",
    defaultTo: "millisiemens",
  },
  electric_conductivity: {
    title: "Electric Conductivity Converter",
    units: units.electric_conductivity,
    convertFn: convertElectricConductivity,
    defaultFrom: "siemens_per_meter",
    defaultTo: "siemens_per_centimeter",
  },
  electrostatic_capacitance: {
    title: "Electrostatic Capacitance Converter",
    units: units.electrostatic_capacitance,
    convertFn: convertElectrostaticCapacitance,
    defaultFrom: "farad",
    defaultTo: "microfarad",
  },
  inductance: {
    title: "Inductance Converter",
    units: units.inductance,
    convertFn: convertInductance,
    defaultFrom: "henry",
    defaultTo: "millihenry",
  },
};
